### PR TITLE
add type declarations

### PR DESCRIPTION
**Pull request by birdue**
also fix two instances of `const` that should've been `let`

I didn't change anything else and the rest of the diff was generated solely because of prettier

### CODE REVIEW

**Comment by mistval** [comment]
Hi, nice, thanks for doing that!

**Comment by mistval** [comment]
Published to NPM as v1.1.0.

**Comment by birdue** [comment]
I just wanted to say, thank you for writing this great package! I've tried a few other packages that do the same thing but they all shoot for accuracy, which inevitably fails for special cases, not to mention situations where there are multiple valid "base forms" to begin with. This package takes a more comprehensive approach which can lead to redundancy, but sometimes this is a necessary tradeoff to obtain all valid results. Good job!

**Comment by mistval** [comment]
I appreciate your saying that =] I'd like to take another look at this project with fresh eyes when I get a chance. There's certainly plenty of room to improve still.

**Pull request merged**
